/*
 * This source file was generated by the Gradle 'init' task
 */
package conta.banco;

public class ContaTerminal {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ContaTerminal().getGreeting());
    }
}
